server:
  port: 8443
  use-forward-headers: true
  ssl:
    key-store: ${keystoreLocation}
    key-store-password: ${keystorePassword}
    key-password: ${keystorePassword}
    key-alias: ${keystoreSSLKey:tomcat}

security:
  require-ssl: true
  basic:
    enabled: false

management:
  security:
    enabled: false

spring:
  profiles:
    active: default, swagger
